name: Wrangler Publish

on:
  push:
    branches:
      - gym-app

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust this to your Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Publish using Wrangler
        run: npx wrangler pages publish dist